### ISSUE TITLE
Неправильно вычисляются единицы измерения

### ISSUE THREAD

**Issue by AlexeyALeonov** [AntonMZ/Storj-Utils#12]
```
 Share_allocated:      2199023255552 GB
 Share_Used:           0 GB
```
На самом деле, в конфиге указано 2TB
https://docs.storj.io/v1.1/discuss/59ec9dd94b12050010127935

**Comment by AntonMZ** [comment]
Resolve!

`
Share_allocated:      1800GB
`
`
Share_Used:           613.5GB
`
