### ISSUE TITLE
Bad number presentation in CLI output

### ISSUE THREAD

**Issue by fragamemnon** [AntonMZ/Storj-Utils#13]
_This case concerns the use of --cli:_

In the `SHARE_ALLOCATED` and `SHARE_USED` sections, the value is presented in bytes, but a metric prefix is added at the end.

For example:
* 100 B are presented as "100 B"
* 100 KB are presented as "100000 KB"
* 100 MB are presented as "100000000 MB", etc...

-------

_Further:_

Since you use base-2 for calculation instead of base-10, the metric prefixes should be correct:
`KiB` instead of `KB`
`MiB` instead of `MB`
`GiB` instead of `GB`
`TiB` instead of `TB`

**Comment by AntonMZ** [comment]
Resolve!
