### ISSUE TITLE
Нужна английская версия инструкции

### ISSUE THREAD

**Issue by AlexeyALeonov** [AntonMZ/Storj-Utils#9]
Пожалуйста, напишите английскую версию инструкции

**Comment by AntonMZ** [comment]
Алексей, инструкция подготовлена и доступна по ссылке https://maxrival.com/how-to-install-and-update-health-bash-script-for-statistic-collection/

Просьба проверить. Если данного материала хватит для размещения на docs.storj.io, то я закрою issue.

**Comment by AlexeyALeonov** [comment]
У меня есть предложение - можно в скрипте использовать такой приём:
сначала перед установкой сделать
```
env > ~/.env
```
потом в скрипте в начале использовать
```
. ~/.env
```
тогда не нужно пути прописывать и при обновлении nvm достаточно снова выполнить команду от пользователя, который будет выполнять скрипт `env > ~/.env`

**Comment by AlexeyALeonov** [comment]
Было бы неплохо иметь эту инструкцию здесь тоже.  Так проще делать pull request.

**Comment by AlexeyALeonov** [comment]
Сделал pull request для скрипта и русской инструкции.
Нужно инструкцию https://maxrival.com/how-to-install-and-update-health-bash-script-for-statistic-collection/ сюда в виде Markdown файла.

**Comment by AntonMZ** [comment]
Инструкция доступна в папке /docs
PullReq с описанием добавил.
PullReq про env видел, изучу.
